apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: vote
spec:
    storageClassName: netapp-file
    accessModes:
    - ReadWriteOnce
    resources:
     requests:
      storage: 5Gi
